#!/usr/bin/env sh

# Concat the trigger together to make it easier to
# track this script itself
TRIGGER_WORD="no"
TRIGGER_WORD+="checkin"
ALT_TRIGGER="auto"
ALT_TRIGGER+="fix"

# Check for trigger word in staged changes
if git diff --cached | grep '^+' | grep -q -i "${TRIGGER_WORD}\|${ALT_TRIGGER}"; then
    echo "Commit rejected: '${TRIGGER_WORD}'|'${ALT_TRIGGER}' found in staged changes."
    exit 1
fi

exit 0
