#!/usr/bin/env sh

# Concat the trigger together to make it easier to
# track this script itself
TRIGGER_WORD="no"
TRIGGER_WORD+="checkin"

# Check for trigger word in staged changes
if git diff --cached | grep -q -i "${TRIGGER_WORD}"; then
    echo "Commit rejected: '${TRIGGER_WORD}' found in staged changes."
    exit 1
fi

exit 0
